<?php
/**
 * Brim LLC
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to support@brimllc.com so we can send you a copy immediately.
 *
 *
 * @category   Brim
 * @package    Brim_Gauges
 * @copyright  Copyright (c) 2012 Brim LLC
 * @license    http://ecommerce.brimllc.com/license-osl
 */
?>
<?php if ($this->helper('brim_gauges')->isEnabled()) : ?>
<script type="text/javascript">
  var _gauges = _gauges || [];
  (function() {
    var t   = document.createElement('script');
    t.type  = 'text/javascript';
    t.async = true;
    t.id    = 'gauges-tracker';
    t.setAttribute('data-site-id', '<?php echo $this->helper('brim_gauges')->getGaugeId(); ?>');
    t.src = '//secure.gaug.es/track.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(t, s);
  })();
</script>
<?php endif; ?>